import type { RegisterDeviceDto } from "./generated/models/RegisterDeviceDto";
import type { SendNotificationDto } from "./generated/models/SendNotificationDto";
import type { NotificationPayloadDto } from "./generated/models/NotificationPayloadDto";

// ─────────────────────────────────────────────
// API Response Wrapper
// All endpoints return this envelope shape:
// { payload: T, statusCode: number, error: null | string }
// ─────────────────────────────────────────────

interface ApiResponse<T> {
  payload: T;
  statusCode: number;
  error: null | string;
}

// ─────────────────────────────────────────────
// Configuration
// ─────────────────────────────────────────────

/**
 * Configuration options for TrioChatNotificationClient.
 * Pass this to the constructor when creating a new client instance.
 */
export interface TrioChatNotificationClientConfig {
  /**
   * JWT / API token for authentication.
   * Generate this from your workspace settings at https://app.triochat.io/
   * Keep this secret — never expose it in client-side bundles.
   */
  token: string;
}

// ─────────────────────────────────────────────
// Device
// ─────────────────────────────────────────────

/**
 * Represents a registered device returned from the TrioChat API.
 * Devices are registered from client apps (React Native, web) and
 * retrieved from the backend to target push notifications.
 */
export interface Device {
  /** MongoDB ObjectId of the device document */
  _id: string;

  /**
   * Unique device identifier generated by TrioChat.
   * Format: `{workspace_id}-{platform}-{timestamp}`
   */
  device_id: string;

  /** Firebase Cloud Messaging token for the device */
  fcm_token: string;

  /** Platform the device is running on */
  platform: "ios" | "android" | "web";

  /**
   * Optional custom metadata attached at registration time.
   * Useful for storing app_version, user_id, device_model, locale, etc.
   */
  metadata?: Record<string, any>;

  /** Workspace this device belongs to */
  workspace_id: string;

  /** ISO timestamp — camelCase format returned by the API */
  createdAt: string;

  /** ISO timestamp — snake_case alias for createdAt */
  created_at: string;

  /** ISO timestamp — camelCase format returned by the API */
  updatedAt: string;

  /** ISO timestamp — snake_case alias for updatedAt */
  updated_at: string;
}

// ─────────────────────────────────────────────
// Response Types
// ─────────────────────────────────────────────

/**
 * Response returned after successfully registering a device.
 * Unwrapped from the API envelope's `payload` field.
 */
export interface RegisterDeviceResponse {
  /** Whether the registration was successful */
  success: boolean;

  /**
   * Unique device identifier assigned by TrioChat.
   * Store this if you want to target this specific device later.
   */
  device_id: string;

  /** Workspace the device was registered under */
  workspace_id: string;
}

/**
 * Response returned after sending a push notification.
 * Unwrapped from the API envelope's `payload` field.
 */
export interface SendNotificationResponse {
  /** Human-readable summary message from the API */
  message: string;

  /** Number of devices the notification was successfully delivered to */
  success_count: number;

  /** Number of devices the notification failed to deliver to */
  failure_count: number;

  /**
   * Per-device delivery results.
   * Only present when targeting specific device_ids.
   */
  results?: Array<{
    device_id: string;
    success: boolean;
    /** Error reason if delivery failed for this device */
    error?: string;
  }>;
}

// ─────────────────────────────────────────────
// Error Class
// ─────────────────────────────────────────────

/**
 * Custom error thrown by all TrioChatNotificationClient methods.
 * Always check `error instanceof TrioPushError` in your catch blocks
 * to get structured error details.
 *
 * @example
 * ```typescript
 * try {
 *   await client.sendNotification({ ... });
 * } catch (error) {
 *   if (error instanceof TrioPushError) {
 *     console.error(error.statusCode); // 401, 404, 500, etc.
 *     console.error(error.message);
 *     console.error(error.response);   // raw API response body
 *   }
 * }
 * ```
 */
export class TrioPushError extends Error {
  constructor(
    message: string,
    /** HTTP status code from the API response (undefined for network errors) */
    public statusCode?: number,
    /** Raw response body from the API */
    public response?: any,
    /** Underlying network/fetch error, if applicable */
    public originalError?: Error,
  ) {
    super(message);
    this.name = "TrioPushError";
    // Restore prototype chain — required when extending built-in Error in TypeScript
    Object.setPrototypeOf(this, TrioPushError.prototype);
  }
}

// ─────────────────────────────────────────────
// Main Client
// ─────────────────────────────────────────────

/**
 * Official client for the TrioChat Push Notification API.
 *
 * Designed to work across all JavaScript environments:
 * Node.js, NestJS, Express, React Native, Bun, Deno, and browsers.
 *
 * Uses native `fetch` — no external dependencies required.
 *
 * ---
 *
 * **Environment guidance:**
 * - `registerDevice()` → call from your **client app** (React Native / web)
 * - `getDevices()` / `sendNotification()` → call from your **backend server only**
 *
 * ---
 *
 * @example
 * ```typescript
 * const client = new TrioChatNotificationClient({
 *   token: process.env.TRIO_PUSH_TOKEN!
 * });
 *
 * // Register a device (client app)
 * await client.registerDevice({
 *   fcm_token: 'firebase-token',
 *   platform: TrioPushPlatform.IOS,
 *   metadata: { app_version: '2.0.0', user_id: 'user-123' }
 * });
 *
 * // Get all devices (backend)
 * const devices = await client.getDevices();
 *
 * // Send a notification (backend)
 * await client.sendNotification({
 *   device_ids: ['device-123'],
 *   notification: { title: 'Hello', body: 'World' }
 * });
 * ```
 */
export class TrioChatNotificationClient {
  private readonly baseUrl = "https://triochat-push.onrender.com";
  private token: string;

  constructor(config: TrioChatNotificationClientConfig) {
    if (!config.token) {
      throw new TrioPushError("Token is required for authentication");
    }
    this.token = config.token;
  }

  // ─────────────────────────────────────────────
  // Private: Core Request Helper
  // ─────────────────────────────────────────────

  /**
   * Internal HTTP helper used by all public methods.
   * Attaches auth headers, serializes the body, parses the response,
   * unwraps the API envelope, and throws `TrioPushError` on failure.
   *
   * @param method - HTTP method
   * @param path   - API path (e.g. '/api/devices')
   * @param body   - Optional request body (will be JSON serialized)
   * @returns Parsed response body typed as T
   */
  private async request<T>(
    method: "GET" | "POST" | "PUT" | "PATCH" | "DELETE",
    path: string,
    body?: unknown,
  ): Promise<T> {
    const url = `${this.baseUrl}${path}`;

    const headers: Record<string, string> = {
      Authorization: `Bearer ${this.token}`,
      "Content-Type": "application/json",
    };

    // Execute the fetch — catch network-level failures (no connection, DNS, etc.)
    const response = await fetch(url, {
      method,
      headers,
      body: body !== undefined ? JSON.stringify(body) : undefined,
    }).catch((err: Error) => {
      throw new TrioPushError(
        `Network error: ${err.message}`,
        undefined,
        undefined,
        err,
      );
    });

    // Parse the response body based on content type
    let responseBody: any;
    const contentType = response.headers.get("content-type") ?? "";

    try {
      responseBody = contentType.includes("application/json")
        ? await response.json()
        : await response.text();
    } catch {
      responseBody = null;
    }

    // Throw a structured error for non-2xx responses
    if (!response.ok) {
      const message =
        (typeof responseBody === "object" && responseBody?.error) ||
        (typeof responseBody === "object" && responseBody?.message) ||
        `Request failed with status ${response.status}`;

      throw new TrioPushError(message, response.status, responseBody);
    }

    return responseBody as T;
  }

  // ─────────────────────────────────────────────
  // Public: Device Registration (📱 Client App)
  // ─────────────────────────────────────────────

  /**
   * Register or update a device's FCM token with TrioChat.
   *
   * Call this from your **client app** (React Native / web) after obtaining
   * the FCM token from Firebase. Safe to call on every app launch since
   * FCM tokens can rotate.
   *
   * @param data - Device registration payload
   * @returns Registration result including the assigned `device_id`
   * @throws {TrioPushError} If the token is invalid or the request fails
   *
   * @example
   * ```typescript
   * const result = await client.registerDevice({
   *   fcm_token: await messaging().getToken(),
   *   platform: TrioPushPlatform.IOS,
   *   metadata: {
   *     app_version: '2.0.0',
   *     user_id: currentUser.id,
   *     device_model: DeviceInfo.getModel()
   *   }
   * });
   *
   * console.log('Registered device:', result.device_id);
   * ```
   */
  async registerDevice(
    data: RegisterDeviceDto,
  ): Promise<RegisterDeviceResponse> {
    const response = await this.request<ApiResponse<RegisterDeviceResponse>>(
      "POST",
      "/api/devices/register",
      data,
    );
    return response.payload;
  }

  // ─────────────────────────────────────────────
  // Public: Device Fetching (🖥️ Backend Only)
  // ─────────────────────────────────────────────

  /**
   * Fetch all registered devices for the authenticated workspace.
   *
   * Returns a flat `Device[]` array — ready to filter, map, or iterate directly.
   * Use this when you don't need the total count.
   *
   * ⚠️ **Backend only** — never call this from a client app.
   *
   * @returns Array of registered devices
   * @throws {TrioPushError} If the request fails
   *
   * @example
   * ```typescript
   * const devices = await client.getDevices();
   *
   * // Find a specific user's device by metadata
   * const userDevice = devices.find(
   *   (d) => d.metadata?.user_id === userId
   * );
   *
   * // Filter by platform
   * const iosDevices = devices.filter((d) => d.platform === TrioPushPlatform.IOS);
   * ```
   */
  async getDevices(): Promise<Device[]> {
    const response = await this.request<ApiResponse<{ devices: Device[] }>>(
      "GET",
      "/api/devices",
    );
    return response.payload.devices;
  }

  // ─────────────────────────────────────────────
  // Public: Send Notification (🖥️ Backend Only)
  // ─────────────────────────────────────────────

  /**
   * Send a push notification to one or more devices.
   *
   * Pass `device_ids` to target specific devices, or omit it to
   * broadcast to **all devices** in the workspace.
   *
   * ⚠️ **Backend only** — never call this from a client app.
   *
   * @param data - Notification payload including recipients and content
   * @returns Delivery result with success/failure counts per device
   * @throws {TrioPushError} If the request fails
   *
   * @example
   * ```typescript
   * // Send to specific devices
   * const result = await client.sendNotification({
   *   device_ids: ['device-123', 'device-456'],
   *   notification: {
   *     title: '💬 New Message',
   *     body: 'John sent you a file'
   *   },
   *   data: { action: 'open_chat', chat_id: '789' }
   * });
   *
   * console.log(`Delivered: ${result.success_count}, Failed: ${result.failure_count}`);
   *
   * // Broadcast to all devices in workspace (omit device_ids)
   * await client.sendNotification({
   *   notification: {
   *     title: '📢 Announcement',
   *     body: 'Scheduled maintenance tonight at 2 AM'
   *   }
   * });
   * ```
   */
  async sendNotification(
    data: SendNotificationDto,
  ): Promise<SendNotificationResponse> {
    const response = await this.request<ApiResponse<SendNotificationResponse>>(
      "POST",
      "/api/notifications/send",
      data,
    );
    return response.payload;
  }

  // ─────────────────────────────────────────────
  // Public: Token Management
  // ─────────────────────────────────────────────

  /**
   * Replace the current authentication token.
   *
   * Use this when your JWT rotates (e.g. after a token refresh)
   * without needing to create a new client instance.
   *
   * @param token - New JWT / API token
   *
   * @example
   * ```typescript
   * client.setToken(await refreshAuthToken());
   * ```
   */
  setToken(token: string): void {
    if (!token) {
      throw new TrioPushError("Token cannot be empty");
    }
    this.token = token;
  }
}

// ─────────────────────────────────────────────
// Re-exports
// ─────────────────────────────────────────────

// Re-export raw DTO types for consumers who need them
export type { RegisterDeviceDto, SendNotificationDto, NotificationPayloadDto };
